### ISSUE TITLE
Is there anyway to enable cursor blinking in QTerminal?

### ISSUE THREAD

**Issue by mlibre** [lxde/qterminal#289] opened 2016-11-28 15:55 UTC
Is there anyway to enable cursor blinking in QTerminal like gnome-terminal?

**Comment by planet36** [comment] 2017-06-18 03:04
https://github.com/lxde/qterminal/issues/259

**Comment by yan12125** [comment] 2017-07-19 05:13
Closing as this is a duplicate of #259.

**Closed by yan12125** 2017-07-19 05:13 UTC
