### ISSUE TITLE
pasting clipboard by context menu takes place in window opened last

### ISSUE THREAD

**Issue by pmattern** [lxde/qterminal#126] opened 2015-02-28 00:39 UTC
If more than one window is open pasting the clipboard by selecting "Paste Clipboard" from QTerminal's context menu always takes place in the window that got opened last no matter in which window the context menu is invoked.
Pasting clipboard by keyboard shortcut isn't affected.

Latest Git versions of both QTermWidget and QTerminal compiled against Qt 5.3.2 or 5.4.0 on Arch Linux x86_64.

**Comment by f2404** [comment] 2016-01-28 13:44
I cannot reproduce the issue: it's working fine for both multiple tabs within one app and multiple qterminal instances running.

**Comment by f2404** [comment] 2016-01-28 14:33
In fact, it looks like any command from the right-click menu is applied to the last window.

**Comment by f2404** [comment] 2016-01-28 16:30
This is happening due to `TabWidget *consoleTabulator` being overwritten on each new window creation, and the already existing one being lost.
I'm not sure what's the reason for that, but I'm guessing that it's the `consoleTabulator` declaration in the form, not in the code:
```
src/forms/qterminal.ui
34:     <widget class="TabWidget" name="consoleTabulator">
```

**Comment by f2404** [comment] 2016-06-02 07:46
Also, qterminal crashes in the following scenario: open qterminal window; open another window and close it; pick an action from the first window context menu (e.g. Copy Selection) -> segfault.
The root cause is the same, segfault should be fixed by the PR.

**Closed** 2016-10-05 19:37 UTC
Labels: bug
