### ISSUE TITLE
xterm style dynamic window title

### ISSUE THREAD

**Issue by Vality** [lxde/qterminal#111] opened 2015-02-19 17:43 UTC
Most graphical terminal emulators support using escape sequences to dynamically set the window title of the emulator as initially implemented in xterm as shown here http://tldp.org/HOWTO/Xterm-Title-3.html

It would be really useful if QTerminal supported this feature as a number of pieces of software benefit from it greatly (some package managers for example use it to provide a progress % on long installs).

I am not sure if it would be better to change the actual window title or just the title of the tab the program is running in. Perhaps one could set the tab title and the window title could be set to the current tab title.

I am also unsure how this could work with split terminals, perhaps use the one currently in focus or perhaps simply disable the feature in tabs containing sub terminals.

Either way, this feature would make QTerminal much more compatible with xterm in terms of feature parity.

Taking a glance over the code of xterm, the actual title change just needs us to `XChangeProperty` the `_NET_WM_NAME` property. 

For more information on the feature please see here:
http://www.tldp.org/HOWTO/text/Xterm-Title

**Comment by pmattern** [comment] 2015-03-19 20:59
This is actually a duplicate of #52, albeit introducing same technical issues not stated before.

**Comment by jleclanche** [comment] 2015-06-12 15:05
PR wanted.

**Comment by pmattern** [comment] 2015-12-07 23:39
Duplicate of #52.

**Closed by pmattern** 2015-12-07 23:39 UTC
Labels: feature requests
