### ISSUE TITLE
Start a tab with custom command

### ISSUE THREAD

**Issue by haskellcamargo** [lxde/qterminal#381] opened 2017-12-29 17:33 UTC
I use `fish` instead of default `bash`. I can start QTerminal directly with it via `qterminal -e fish`.

A cool feature would be having the possibility to set the custom command in the preferences window, and that this command could also be applied to new tabs.

**Comment by yan12125** [comment] 2017-12-30 02:23
Duplicate of #354. You can override $SHELL to always use ```fish```

**Closed by yan12125** 2017-12-30 02:23 UTC
