### ISSUE TITLE
decrease minimal height

### ISSUE THREAD

**Issue by excalibur1234** [lxde/qterminal#263] opened 2016-09-27 21:01 UTC
qterminal has a minimal height and width.
can its minimal height be decrease to e.g. the height of 2 lines?

i have many small scripts (e.g. to download youtube videos) and i like to run them in qterminal to see how much the script has progressed. but i do not need to see 12 lines of code (i see 12 lines of code in qterminal at minimum height with my current font size). 2 lines of code would be perfect.

i have used konsole for a short amount of time and it has a much lower minimal height. now, i miss such a feature in qterminal.

**Comment by jcc242** [comment] 2016-10-01 04:26
Just familiarizing myself with the code, decided to take a look at this. Removed the minimumSize property from TabWidget in qterminal.ui. See attached screenshot, top terminal is konsole for comparison, bottom terminal is qterminal. To the right is the absolute minimum size I could shrink them both to.

I could commit this and file a pull request if desired. Do we want to specify a minimum width/height? I think it would be more difficult to specify minumum number of lines as it changes based on the font size, would need a signal/slot on font size change. Original minimum size is 320x200 (pixels?).

![qterm-height](https://cloud.githubusercontent.com/assets/2275469/19011715/19e20df8-875c-11e6-9ccb-22ce0ed2e8f6.png)

**Comment by excalibur1234** [comment] 2016-10-01 10:20
wow, this looks great!

i think a minimum height/width is useful. specifying them in pixels is ok. 
i was mentioning "two line minimum height" more as a reference than something you would need to write code for.

200 pixels as the current minimum height sounds about right. this is about 1/5 of a 1920x1080 screen. as mentioned above, this is ok for doing terminal work, but not when you want a pop-up of qterminal in a screen edge with a progress bar of your running script.

i recommend to do a pull request and refer add a short text like "this PR solves #263". then, the lxqt team can discuss the advantages and disadvantages of your change.

**Comment by Vladimir-csp** [comment] 2016-10-08 03:56
Dupe of #181.
I find terminals without menus or scrollbars (or anything except the terminal itself) very handy, as they can be resized down to 1 short line to show some terse useful output.
No minimal size should be set, just increment window size hints.

**Comment by agaida** [comment] 2016-11-20 16:36
Closed with #265

**Closed by agaida** 2016-11-20 16:36 UTC
